// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wdwybovxhpwokhjcuwlr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indkd3lib3Z4aHB3b2toamN1d2xyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk0NDg1MTgsImV4cCI6MjA3NTAyNDUxOH0.wh6tS_9X6Dou-eOYxo7ebydIOsmo9jQPJJgTHoMPs88";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});